# Generated by Django 4.2.9 on 2024-02-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='qs',
            field=models.JSONField(default=list),
        ),
    ]
