# Generated by Django 4.2.9 on 2024-02-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_survey_qs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
